name: MacOS

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.env.os }}
    env:
      VERSION: 0.1.0
    strategy:
      matrix:
        env:
          - name: MacOS
            os: macos-11
            qtplatform: mac
            qtversion: 5.15.2
            arch: darwin64-x86_64-cc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Installing Qt
        uses: jurplel/install-qt-action@v2.13.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        timeout-minutes: 10
        with:
          version: ${{ matrix.env.qtversion }}
          target: desktop
          host: ${{ matrix.env.qtplatform }}
          install-deps: true

      - name: Installing dependencies
        id: vars
        run: |
          git clone https://github.com/lxqt/lxqt-build-tools.git
          cd lxqt-build-tools
          mkdir build
          cmake -S . -B ./build '-DCMAKE_GENERATOR:STRING=Unix Makefiles'
          cmake --build build/ --target all
          cd build/
          make install
          cd ../../

      - name: Build QTermWidget
        run: |
          mkdir build
          cmake -S . -B ./build '-DCMAKE_GENERATOR:STRING=Unix Makefiles'
          cmake --build build/ --target qtermwidget5
          cp build/libqtermwidget5.1.*.dylib build/lib/libqtermwidget.dylib

      - name: Uploading QTermWidget
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/lib/*.dylib

      - name: Prune previous runs
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const days_to_expiration = 30;
            const ms_in_day = 86400000;
            const now = Date.now();
            const pages = 5;

            // we don't want to prune old runs from test.yml
            // because we track the duration of runs over time

            const workflows = [
              'macos.yml'
            ]

            let runs_to_delete = [];

            for (const workflow of workflows) {
              for (let page = 0; page < pages; page += 1) {
                let response = await github.actions.listWorkflowRuns({
                  owner: context.repo.owner,
                  page: page,
                  per_page: 100,
                  repo: context.repo.repo,
                  workflow_id: workflow
                });

                if (response.data.workflow_runs.length > 0) {
                  for (const run of response.data.workflow_runs) {
                    if (run.head_branch == "${{ steps.vars.outputs.short_ref }}" && run.head_sha != "${GITHUB_SHA}") {
                      runs_to_delete.push([run.id, run.name]);
                    }
                  }
                }
              }
            }

            for (const run of runs_to_delete) {
              console.log(`Run id ${run[0]} of '${run[1]}' is older than ${days_to_expiration} days. Deleting...`);
              try {
                await github.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run[0]
                });
              } catch (error) {
                // ignore errors
              }
            }
